apiVersion: v1
kind: Namespace
metadata:
  name: cawsay-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cowsay
  name: cowsay
  namespace: cawsay-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowsay
  strategy: {}
  template:
    metadata:
      labels:
        app: cowsay
    spec:
      containers:
        - image: danielguo/cowsay-web-app:latest
          imagePullPolicy: IfNotPresent
          name: cowsay
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cowsay
  name: cowsay
  namespace: cawsay-ns
spec:
  ports:
    - port: 8080
  selector:
    app: cowsay
---
# The resources beyond is for testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: test:latest
          imagePullPolicy: IfNotPresent
          name: cowsay
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: var
  name: var
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      labels:
        app: var
    spec:
      containers:
      - image: myimage
        name: myimage
        command: [ "start", "--host", "$(MY_SERVICE_NAME)" ]
        env:
          - name: SECRET_TOKEN
            value: $(SOME_SECRET_NAME)