############################################
# Usage:
# docker build -f Dockerfile -t danielguo/cow-say-template:v1 .
# docker push danielguo/cow-say-template:v1
############################################
FROM scratch

COPY ytt/templates templates