---
apiVersion: v1
kind: Secret
metadata:
  name: test-app-values-secret
type: Opaque
stringData:
  values.yaml: |
    #@data/values
    ---
    nginx:
      replicas: 3
    cronTab:
      cronSpec: "* * * * */3"