apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: job-propagation
spec:
  resourceSelectors:
    - apiVersion: batch/v1
      kind: Job
      name: parallel-sleep-job
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
