# Creates a cluster with one control-plane node and one worker node
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: DockerCluster
metadata:
  name: CLUSTER_NAME
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: CLUSTER_NAME
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: KubeadmControlPlane
    name: CLUSTER_NAME-controlplane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: DockerCluster
    name: CLUSTER_NAME
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: DockerMachineTemplate
metadata:
  name: CLUSTER_NAME-controlplane
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: "controlplane.cluster.x-k8s.io/v1alpha4"
kind: KubeadmControlPlane
metadata:
  name: CLUSTER_NAME-controlplane
  namespace: default
spec:
  replicas: 1
  version: "v1.22.0"
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: DockerMachineTemplate
    name: CLUSTER_NAME-controlplane
    namespace: default
  kubeadmConfigSpec:
    clusterConfiguration:
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: DockerMachineTemplate
metadata:
  name: CLUSTER_NAME-worker
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
kind: KubeadmConfigTemplate
metadata:
  name: CLUSTER_NAME-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: MachineDeployment
metadata:
  name: CLUSTER_NAME-md-0
  labels:
    cluster.x-k8s.io/cluster-name: CLUSTER_NAME
spec:
  clusterName: "CLUSTER_NAME"
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: "CLUSTER_NAME"
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: "CLUSTER_NAME"
    spec:
      version: "v1.22.0"
      clusterName: "CLUSTER_NAME"
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha4
          kind: KubeadmConfigTemplate
          name: CLUSTER_NAME-md-0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
        kind: DockerMachineTemplate
        name: CLUSTER_NAME-worker