version: "3.7"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    env_file:
      - bookstack-ldap.env
    volumes:
      - /config
    ports:
      - 6875:80
    restart: always
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    env_file:
      - bookstack-db-variables.env
    volumes:
      - /config
    restart: always
